flaskbackend/website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required
from flask_login import current_user
from flask_login import login_user
from flask_login import logout_user
from .models import Usuario, Task, Project, RelUsuarioProject, ChecklistItem, Notification
from flask import jsonify, request
from datetime import datetime


from werkzeug.security import generate_password_hash, check_password_hash
from . import db 
from .models import Usuario, Project

auth = Blueprint('auth',__name__)

@auth.route('/', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        data = request.form
        email = data.get('emailLogin')
        senha = data.get('passwordLogin')

        # Verifica se os campos foram preenchidos
        if not email or not senha:
            flash("Por favor, preencha todos os campos", category='error')
            return redirect(url_for('auth.login'))  # Retorna para a tela de login

        # Verifica se o usuário existe no banco de dados
        user = Usuario.query.filter_by(email=email).first()

        if not user:
            flash("Usuário inexistente! Faça cadastro antes", category='error')
            return redirect(url_for('auth.signup'))  # Redireciona para a página de cadastro
        else:
            # Verifica se a senha está correta
            if check_password_hash(user.password, senha):
                flash("Login bem sucedido", category='success')

                # Loga o usuário na sessão
                login_user(user)

                return redirect(url_for('auth.home'))  # Redireciona para a página principal
            else:
                flash("Senha incorreta", category='error')

    return render_template('login.html')


@auth.route('/home', methods=['POST', 'GET'])
@login_required
def home():
    if request.method == 'POST':
        nome_projeto = request.form.get('projeto')
        
        if not nome_projeto:
            flash('O nome do projeto é obrigatório.', category='error')
            return redirect(url_for('auth.home'))
        
        projeto_existente = Project.query.filter_by(nome_projeto=nome_projeto, user_id=current_user.id).first()

        if projeto_existente:
            flash("Já existe um projeto com esse nome", category='error')
        else:
            projeto_novo = Project(nome_projeto=nome_projeto, user_id=current_user.id)
            db.session.add(projeto_novo)
            try:
                db.session.commit()
                # Adiciona uma notificação
                nova_notificacao = Notification(user_id=current_user.id, content=f'Projeto "{nome_projeto}" foi criado.')
                db.session.add(nova_notificacao)
                db.session.commit()
                flash('Projeto criado com sucesso!', category='success')
            except Exception as e:
                db.session.rollback()
                flash('Erro ao salvar o projeto.', category='error')

        return redirect(url_for('auth.home'))

    # Obter todos os projetos do usuário
    projetos_criados = Project.query.filter_by(user_id=current_user.id).all()
    projetos_compartilhados = current_user.projects
    todos_os_projetos = projetos_criados + projetos_compartilhados

    return render_template('taskMaster.html', projects=todos_os_projetos)



@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        email = request.form.get('emailsignup')
        senha = request.form.get('passwordsignup')

        # Debug prints
        print(email)
        print(senha)

        user = Usuario.query.filter_by(email=email).first()

        if user:
            flash("Usuário já cadastrado! Faça Login", category='error')
            return redirect(url_for('auth.login'))

        if len(senha) < 10:
            flash("A senha deve ter pelo menos 10 caracteres", category='error')
            return redirect(url_for('auth.signup'))
        else:
            novo_user = Usuario(email=email, password=generate_password_hash(senha, method='pbkdf2:sha256', salt_length=8))

            db.session.add(novo_user)
            db.session.commit()

            flash("Usuário cadastrado com sucesso", category='success')

            return redirect(url_for('auth.login'))

    return render_template('signup.html')


@auth.route('/logout')
@login_required
def logout():
    logout_user()  # Encerra a sessão do usuário
    return render_template('login.html')



@auth.route('/sobre')
@login_required
def sobre():
    return render_template('sobre.html')


    # Simulação de armazenamento de projetos (dicionário para projetos)
projects = {}



# Projeto e Task
@auth.route('/projeto/<int:project_id>', methods=['GET', 'POST'])
@login_required
def gerenciar_projeto(project_id):
    projeto = Project.query.get_or_404(project_id)

    if request.method == 'POST':
        task_name = request.form.get('task_name')
        task_status = request.form.get('task_status')
        comment = request.form.get('comment')
        drive_link = request.form.get('drive_link')

        try:
            importance = int(request.form.get('importance'))
            ease = int(request.form.get('ease'))
        except (TypeError, ValueError):
            flash('Valores de importância e facilidade inválidos.', 'error')
            return redirect(url_for('auth.gerenciar_projeto', project_id=project_id))

        completion_date = request.form.get('completion_date')
        if not completion_date:
            flash('Data de conclusão é obrigatória.', 'error')
            return redirect(url_for('auth.gerenciar_projeto', project_id=project_id))

        try:
            completion_date = datetime.strptime(completion_date, '%Y-%m-%d').date()
        except ValueError:
            flash('Data de conclusão inválida. Use o formato YYYY-MM-DD.', 'error')
            return redirect(url_for('auth.gerenciar_projeto', project_id=project_id))

        if task_name and task_status and importance and ease:
            priority = importance * ease
            nova_tarefa = Task(description=task_name, status=task_status, project_id=projeto.id,
                               importance=importance, ease=ease, priority=priority,
                               completion_date=completion_date, comment=comment,
                               drive_link=drive_link)
            db.session.add(nova_tarefa)
            db.session.commit()

            # Adiciona uma notificação
            nova_notificacao = Notification(user_id=current_user.id, content=f'Tarefa "{task_name}" adicionada ao projeto "{projeto.nome_projeto}".')
            db.session.add(nova_notificacao)
            db.session.commit()
            flash('Tarefa adicionada com sucesso!', 'success')
        else:
            flash('Todos os campos são obrigatórios.', 'error')

        return redirect(url_for('auth.gerenciar_projeto', project_id=project_id))

    prereq_tasks = Task.query.filter_by(project_id=projeto.id, status='Pré-requisitos').order_by(Task.priority.desc()).all()
    in_prod_tasks = Task.query.filter_by(project_id=projeto.id, status='Em Produção').order_by(Task.priority.desc()).all()
    completed_tasks = Task.query.filter_by(project_id=projeto.id, status='Concluído').order_by(Task.priority.desc()).all()

    return render_template('project_details1.html', project=projeto,
                           prereq_tasks=prereq_tasks, in_prod_tasks=in_prod_tasks, 
                           completed_tasks=completed_tasks)

    
@auth.route('/editar_projeto/<int:project_id>', methods=['GET', 'POST'])
@login_required
def editar_projeto(project_id):
    projeto = Project.query.get_or_404(project_id)
    
    if request.method == 'POST':
        novo_nome = request.form.get('project_name')
        
        if not novo_nome:
            flash('O nome do projeto não pode ser vazio.', category='error')
        else:
            nome_antigo = projeto.nome_projeto  # Armazenar o nome antigo do projeto
            projeto.nome_projeto = novo_nome
            db.session.commit()
            
            # Adicionar notificação informando a atualização do nome do projeto
            nova_notificacao = Notification(
                user_id=current_user.id,
                content=f'O projeto "{nome_antigo}" foi atualizado para "{novo_nome}".'
            )
            db.session.add(nova_notificacao)
            db.session.commit()
            
            flash('Projeto atualizado com sucesso!', category='success')
            return redirect(url_for('auth.home'))
    
    return render_template('editar_projeto.html', projeto=projeto)


@auth.route('/deletar_projeto/<int:project_id>', methods=['POST'])
@login_required
def deletar_projeto(project_id):
    projeto = Project.query.get_or_404(project_id)
    
    # Buscar todas as tarefas associadas ao projeto
    tarefas = Task.query.filter_by(project_id=project_id).all()
    
    try:
        # Deletar todas as tarefas associadas ao projeto
        for tarefa in tarefas:
            db.session.delete(tarefa)
        
        # Remover o projeto
        db.session.delete(projeto)
        # Adicionar notificação
        nova_notificacao = Notification(user_id=current_user.id, content=f'O projeto "{projeto.nome_projeto}" foi deletado.')
        db.session.add(nova_notificacao)
        db.session.commit()
        db.session.commit()
        
        flash('Projeto e todas as tarefas associadas deletados com sucesso!', category='success')
    except Exception as e:
        db.session.rollback()
        flash('Erro ao deletar o projeto e as tarefas associadas.', 'error')

    return redirect(url_for('auth.home'))




flaskbackend/website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}TaskMaster{% endblock %}</title>
    <link rel="stylesheet" href="{{url_for('static',filename='taskMaster.css')}}">
    {% block styles %}{% endblock %}
</head>
<body>

    <header>
        <div class="containerTask">
            <h1>TaskMaster</h1>
            <ul>
                <li><a href="{{ url_for('auth.home') }}">Home</a></li>
                <li><a href="{{ url_for('auth.sobre') }}">Sobre</a></li>
                <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                <li>
                    <!-- NOTIFICAÇÃO para ficar mais facil -->
                    <a href="{{ url_for('auth.notificacoes') }}" class="notification-icon">
                        🔔
                    </a>
                </li>
                
            </ul>
        </div>
    </header>


    <div class="container main">
        {% block content %}{% endblock %}
    </div>

    <script src="{{url_for('static', filename='taskMaster.js')}}"></script>
    {% block scripts %}{% endblock %}
</body>
</html>

flaskbackend/website/templates/checklist.html
{% extends 'base.html' %}

{% block title %}
TaskMaster - Checklist
{% endblock %}

{% block content %}
    <h2>Checklist da Tarefa: {{ tarefa.description }}</h2>
    <h3>Projeto: {{ projeto.nome_projeto }}</h3>

    <div class="checklist-container">
        <form method="POST" action="{{ url_for('auth.atualizar_checklist', task_id=tarefa.id_task, project_id=projeto.id) }}">
            <ul class="checklist-items">
                {% for item in tarefa.checklist_items %}
                <li>
                    <input type="checkbox" id="item_{{ item.id }}" name="checklist_items" value="{{ item.id }}" {% if item.completed %}checked{% endif %}>
                    <label for="item_{{ item.id }}">{{ item.description }}</label>

                    <!-- Estrutura de tabela para os botões de edição e exclusão -->
                    <table style="display:inline; margin-left: 10px;">
                        <tr>
                            <td>
                                <!-- Botão para editar o nome do item -->
                                <button type="button" class="btn btn-primary" onclick="toggleEdit({{ item.id }})">Editar Nome</button>
                            </td>
                            <td>
                                <!-- Formulário para excluir o item -->
                                <form method="POST" action="{{ url_for('auth.excluir_checklist', item_id=item.id, task_id=tarefa.id_task) }}" style="display:inline;">
                                    <button type="submit" class="btn btn-danger" onclick="return confirm('Tem certeza que deseja deletar este item?');">Excluir</button>
                                </form>
                            </td>
                        </tr>
                    </table>

                    <!-- Campo de edição que ficará oculto inicialmente -->
                    <form method="POST" action="{{ url_for('auth.alterar_item_checklist', item_id=item.id, task_id=tarefa.id_task) }}" class="inline-form" id="edit-form-{{ item.id }}" style="display:none;">
                        <input type="text" name="novo_nome_item" placeholder="Novo nome" required>
                        <button type="submit">Alterar Nome</button>
                    </form>
                </li>
                {% endfor %}
            </ul>
            <div class="button-group">
                <button type="submit">Salvar Checklist</button>
                <button type="button" id="marcar-todas">Marcar Todas</button>
                <button type="button" id="desmarcar-todas">Desmarcar Todas</button>
            </div>
        </form>
        
        <!-- Formulário para adicionar novo item -->
        <form method="POST" action="{{ url_for('auth.adicionar_item_checklist', task_id=tarefa.id_task) }}">
            <input type="hidden" name="project_id" value="{{ projeto.id }}">  <!-- Campo oculto para o project_id -->
            <input type="text" name="descricao_item" placeholder="Descrição do novo item" required class="descricao-item-input">
            <div class="button-group">
                <button type="submit">Adicionar Item</button>
                <a href="{{ url_for('auth.gerenciar_projeto', project_id=projeto.id) }}" class="button-link">Voltar ao Projeto</a>
            </div>
        </form>
    </div>
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{{ url_for('static', filename='checklist.css') }}">
{% endblock %}

{% block scripts %}
    <script src="{{ url_for('static', filename='checklist.js') }}"></script>
{% endblock %}

flaskbackend/website/templates/editar_projeto.html
{% extends 'base.html' %}

{% block title %}
Editar Projeto - {{ projeto.nome_projeto }}
{% endblock %}

{% block content %}
    <h2>Editar Projeto</h2>
    
    <form id="criarProjeto" method="POST" action="{{ url_for('auth.editar_projeto', project_id=projeto.id) }}">
        <input type="text" name="project_name" value="{{ projeto.nome_projeto }}" required>
        <button type="submit">Salvar Alterações</button>
    </form>
{% endblock %}

flaskbackend/website/templates/esqueceu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Recuperar Senha</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='esqueceu.css') }}">
</head>
<body>

    <!-- Uma div que guarda todo o conteúdo da página -->
    <div class='container'>
        <div class='form-container' id='loginContainer'>
            <form action="/esqueceu" method="POST" id='loginForm'>
                <!-- Campo de email -->
                <label for="loginEmail" class="form-label">Email:</label>
                <input type="email" id="loginEmail" class="form-control" name="emailEsqueceu" placeholder="Entre email">
            
                <!-- Campo de nova senha -->
                <label for="loginPassword">Sua nova Senha:</label>
                <input type="password" id="loginPassword" class="form-control" name="senha1" placeholder="Entre password">
            
                <!-- Campo de confirmação da nova senha -->
                <label for="loginPassword">Sua nova Senha novamente:</label>
                <input type="password" id="loginPassword" class="form-control" name="senha2" placeholder="Entre password">
            
                <!-- Botão de envio -->
                <button type="submit" class="btn btn-primary">Mudar</button>
            
            
                <!-- Link estilizado como botão -->
                <a href="{{ url_for('auth.login') }}" class="btn btn-secondary" role="button">Login</a>



            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <div class="flash-messages">
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                            {{ message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
            {% endwith %}    
            </form>
        </div>
    </div>
    <!-- Scripts do Bootstrap (necessário para o funcionamento do botão de fechar nos alerts) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>

flaskbackend/website/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='login.css') }}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.6.0/css/bootstrap.min.css">
</head>
<body>

    <div class='container'>
        <div class='form-container' id='loginContainer'>
            <form action="/" method="POST" id='loginForm'>
                <h2>Login</h2>
                
                <div class="mb-3">
                    <label for="loginEmail" class="form-label">Email:</label>
                    <input type="email" id="loginEmail" class="form-control" name="emailLogin" placeholder="Entre email">
                </div>

                <div class="input-group">
                    <label for="loginPassword">Senha:</label>
                    <input type="password" id="loginPassword" class="form-control" name="passwordLogin" placeholder="Entre password">
                </div>
                
                <button type="submit" class="btn btn-primary">Login</button>
                <a href="{{ url_for('auth.signup') }}" class="btn btn-secondary" role="button">Ir para Cadastro</a>
                <a href="{{ url_for('auth.esqueceu') }}" class="btn btn-secondary" role="button">Esqueceu a senha</a>

            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    <div class="flash-messages">
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                                {{ message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span>&times;</span>
                                </button>                                
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}
            {% endwith %}
            </form>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.6.0/js/bootstrap.min.js"></script>
    <script>
        $(document).ready(function(){
            $('.alert-dismissible .close').on('click', function() {
                $(this).closest('.alert').fadeOut();
            });
        });
    </script>

</body>
</html>

flaskbackend/website/templates/notificacoes.html
{% extends 'base.html' %}

{% block title %}
TaskMaster - Gerenciamento de Projetos
{% endblock %}

{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Notificações</title>
    <!-- Importando o CSS externo -->
    <link rel="stylesheet" href="{{ url_for('static', filename='notificacao.css') }}">
</head>
<body>
    <div class="notification-container">
        <h2>Notificações</h2>
        
        {% for notificacao in notificacoes %}
            <div class="update">
                <p>{{ notificacao.content }}</p>
                <p class="date">Data: {{ notificacao.created_at.strftime('%d/%m/%Y %H:%M') }}</p>
            </div>
        {% else %}
            <p>Nenhuma notificação disponível.</p>
        {% endfor %}
    </div>
</body>
{% endblock %}

flaskbackend/website/templates/notifications.html
{% extends 'base.html' %}

{% block title %}
TaskMaster - Gerenciamento de Projetos
{% endblock %}

{% block content %}
    <h2>Fazer as notificações aparecer não sei como boa sorte :)</h2>

    

    
    <script src="{{ url_for('static', filename='compartilhar.js') }}"></script>
{% endblock %}

flaskbackend/website/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='login.css') }}">
</head>
<body>

    <!-- Uma div que guarda todo o conteúdo da página -->
    <div class='container'>
        <div class='form-container' id='signupContainer'>
            <form action="/signup" method="POST" id="signupForm">
                <!-- Título do formulário -->
                <h2>Cadastro</h2>
                
                <div class="mb-3">
                    <!-- Texto que aparece à esquerda da caixa de input -->
                    <label for="signupEmail" class="form-label">Email:</label>

                    <input type="email" id="signupEmail" class="form-control"
                    name="emailsignup" placeholder="Entre com o email" required>
                </div>

                <div class="input-group">
                    <!-- Texto que aparece antes da caixa de input senha -->
                    <label for="signupPassword">Senha:</label>
                    <input type="password" id="signupPassword" class="form-control"
                    name="passwordsignup" placeholder="Entre com a senha" required>
                </div>
                
                <!-- Botão para submeter o formulário -->
                <button type="submit" class="btn btn-primary">Cadastrar</button>

                <a href="{{ url_for('auth.login') }}" class="btn btn-secondary" role="button">Ir para Login</a>


                <!-- Exibe mensagens flash -->
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <div class="flash-messages">
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                            {{ message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
            {% endwith %}

            </form>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>

flaskbackend/website/templates/sobre.html
{% extends 'base.html' %}

{% block title %}
TaskMaster - Sobre
{% endblock %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='sobre.css') }}">
    <h2>Sobre o TaskMaster</h2>

    <p style="text-align: justify;">
        A aplicação visa fornecer uma interface onde o usuário pode priorizar suas tarefas. Como ocorre essa priorização?
        Ao adicionar uma nova atividade, o usuário atribui uma pontuação de 1, 3, 5, 8 ou 13 para Importância (13 é a mais importante e 1 a menos importante) e Facilidade (1 é a mais difícil e 13 a mais fácil).
    </p>

    <p style="text-align: justify;">
        A prioridade é calculada multiplicando os níveis de Facilidade e Importância, sendo a atividade com o maior resultado a de maior prioridade.
        Dessa forma, uma atividade com pontuação 13 em ambos os critérios deve ser realizada primeiro, pois é a mais importante e a mais fácil.
    </p>

    <p style="text-align: justify;">
        Do contrário, uma atividade difícil e pouco importante (nível 1) deve ser feita por último, estando no nível mais baixo de prioridade.
    </p>
{% endblock %}

flaskbackend/website/templates/taskMaster.html
{% extends 'base.html' %}

{% block title %}
TaskMaster - Gerenciamento de Projetos
{% endblock %}

{% block content %}
    <h2>Gerenciamento de Projetos</h2>

    <form id="criarProjeto" method="POST" action="{{ url_for('auth.adicionar_projeto') }}">
        <input type="text" name="project_name" placeholder="Nome do Projeto" required>
        <button type="submit">Criar Projeto</button>
    </form>

    <h3>Projetos</h3>
    <table id="botoesProjetos">
        <tr>
            <th>Nome do Projeto</th>
            <th>Ações</th>
        </tr>
        {% for projeto in projects %}
        <tr>
            <td>{{ projeto.nome_projeto }}</td>
            <td>
                <a href="/projeto/{{ projeto.id }}" class="btn btn-primary">Gerenciar</a>
                <a href="{{ url_for('auth.editar_projeto', project_id=projeto.id) }}" class="btn btn-warning">Editar</a>
            
                <!-- Formulário para deletar projeto via POST -->
                <form method="POST" action="{{ url_for('auth.deletar_projeto', project_id=projeto.id) }}" style="display:inline;">
                    <button type="submit" class="btn btn-danger" onclick="return confirm('Tem certeza que deseja deletar este projeto?');">Deletar</button>
                </form>
            
                <!-- Botão para abrir o formulário de compartilhamento -->
                <button class="btn btn-compartilhar" onclick="mostrarFormulario('{{ projeto.id }}')">Compartilhar</button>

                <!-- Formulário de compartilhamento escondido -->
                <div id="compartilhar-form-{{ projeto.id }}" style="display:none; margin-top: 10px;">
                    <form method="POST" action="{{ url_for('auth.compartilhar_projeto', project_id=projeto.id) }}">
                        <input type="email" name="emailShare" placeholder="Digite o email" required style="padding: 5px; margin-right: 5px;">
                        <button type="submit" class="btn btn-envicom">Enviar</button>
                    </form>
                    
                </div>
            </td>
            
        </tr>
        {% endfor %}
    </table>
    <script src="{{ url_for('static', filename='compartilhar.js') }}"></script>
{% endblock %}